debug: true
spring:
  flyway:
    enabled: true
    clean-disabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_rbac
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: now()
      logic-not-delete-value: 'null'
  type-aliases-super-type: com.example.demo.dataobject.BasicDO