mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: now()
      logic-not-delete-value: 'NULL'
  type-enums-package: com.example.demo.enums
  mapper-locations: classpath*:/mapper/**/*.xml